GET http://localhost:4000/

### 

GET http://localhost:4000/add-user

###
POST http://localhost:4000/login?email=quocvinguyen.official@gmail.com&password=Mapde925

###
POST http://localhost:4000/posted

###
POST http://localhost:4000/login

### 
GET http://localhost:4000/getSampleRespond

### 
GET http://localhost:4000/add-order